auth:
  rootUserEmail: "admin@your.org"
  initialPassword: "superSecretPassword123!"


ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: openobserve.test.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


livenessProbe:
  httpGet:
    path: /healthz
    port: 5080
  initialDelaySeconds: 10
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /healthz
    port: 5080
  initialDelaySeconds: 5
  periodSeconds: 3