apiVersion: v1
kind: Secret
metadata:
  name: "initial-root-password"
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ include "openobserve.initialPassword" . | b64enc | quote }}
